// src/routes/resume/index.svelte
<script context="module" lang="ts">
  import "../../tailwind.css";

  import allWorkExperiences from "../../data/resume/work.yml";
  import allOpenSourceProjects from "../../data/resume/open-source.yml";

  const workExperiences = allWorkExperiences.filter((work) => !work.hide);
  const openSourceProjects = allOpenSourceProjects.filter((project) => !project.hide);
</script>

<svelte:head>
  <title>Resume for Alex LaFroscia</title>

  <meta charSet="utf-8" />
  <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</svelte:head>

<header
  class="w-readable max-w-full mx-auto px-4 sm:px-8 flex flex-col my-8 md:flex-row md:justify-between"
>
  <h1 class="text-3xl font-bold text-center md:text-left">Alex LaFroscia</h1>
  <div class="flex justify-center md:flex-col md:items-end">
    <a class="mr-4 text-right md:mr-0" href="/">alexlafroscia.com</a>
    <a class="md:text-right" href="mailto:alex@lafroscia.com"> alex@lafroscia.com </a>
  </div>
</header>

<section class="w-readable max-w-full mx-auto px-4 sm:px-8 mb-8 space-y-4">
  <header>
    <h1 class="text-xl font-bold text-center md:text-left">Work Experience</h1>
  </header>

  {#each workExperiences as work}
    <div class="items-center grid gap-x-4 gap-y-1 work-container">
      <h2 class="work-company font-bold">{work.company}</h2>
      <p class="work-role">{work.role}</p>
      <p class="work-time">{work.time}</p>
      <ul class="work-details list-disc ml-5 space-y-1">
        {#each work.details as detail}
          <li class="work-detail">{detail}</li>
        {/each}
      </ul>
    </div>
  {/each}
</section>

<section class="w-readable max-w-full mx-auto px-4 sm:px-8 mb-8 space-y-4">
  <header>
    <h1 class="text-xl font-bold text-center md:text-left">Open Source</h1>
  </header>

  {#each openSourceProjects as project}
    <div>
      <h2><a class="font-bold" href={`https://github.com/${project.name}`}>{project.name}</a></h2>
      <ul class=" list-disc ml-5 space-y-1">
        {#each project.details as detail}
          <li>{detail}</li>
        {/each}
      </ul>
    </div>
  {/each}
</section>

<section class="w-readable max-w-full mx-auto px-4 sm:px-8 mb-8 space-y-4">
  <header>
    <h1 class="text-xl font-bold text-center md:text-left">Academics</h1>
  </header>
  <ul>
    <li>
      BS in Computed Science from University of Pittsburgh, College of Arts and Sciences, Class of
      2016.
    </li>
  </ul>
</section>

<style>
  @media print {
    :global(html) {
      font-size: 12px;
    }
  }

  .work-container {
    grid-template-areas:
      "name name name"
      "role role role"
      "time time time"
      "details details details";
    grid-template-columns: auto 1fr auto;

    @screen sm {
      grid-template-areas:
        "name name name"
        "role role time"
        "details details details";
    }

    @screen md {
      grid-template-areas:
        "name role time"
        "details details details";
    }
  }

  .work-company {
    grid-area: name;
  }

  .work-role {
    grid-area: role;
  }

  .work-time {
    grid-area: time;
  }

  .work-details {
    grid-area: details;
  }

  .work-detail :global(span) {
    @apply leading-5;
  }
</style>

// src/pages/resume.jsx
import React from "react";
import { graphql } from "gatsby";
import Markdown from "markdown-to-jsx";
import { Global, css } from "@emotion/core";
import styled from "@emotion/styled";

import Section from "../elements/section";

const SectionHeader = styled.h2`
  text-align: center;
  margin-bottom: 0;

  @media (min-width: 700px) {
    text-align: left;
    margin-bottom: 1em;
  }
`;

const ContactGroup = styled.div`
  column-gap: 1em;
  display: grid;
  grid-template-areas: "name name" "website email";
  row-gap: 0.25em;

  @media (min-width: 700px) {
    grid-template-areas: "name website" "name email";
    margin: 2em 6em;
  }
`;

const Name = styled.h1`
  grid-area: name;
  margin: 0;
  text-align: center;

  @media (min-width: 700px) {
    text-align: left;
  }
`;

const Website = styled.span`
  grid-area: website;
  text-align: right;
`;

const Email = styled.span`
  grid-area: email;

  @media (min-width: 700px) {
    text-align: right;
  }
`;

const Work = ({ work }) => (
  <div
    css={css`
      align-items: center;
      column-gap: 1em;
      display: grid;
      grid-template-areas:
        "name name name"
        "role role role"
        "time time time"
        "details details details";
      grid-template-columns: auto 1fr auto;
      margin-bottom: 1em;
      row-gap: 0.25em;

      @media (min-width: 450px) {
        grid-template-areas:
          "name name name"
          "role role time"
          "details details details";
      }

      @media (min-width: 700px) {
        grid-template-areas:
          "name role time"
          "details details details";
      }
    `}
  >
    <h3
      css={css`
        grid-area: name;
        margin: 0;
      `}
    >
      {work.company}
    </h3>
    <p
      css={css`
        grid-area: role;
        margin: 0;
      `}
    >
      {work.role}
    </p>
    <p
      css={css`
        grid-area: time;
        margin: 0;
      `}
    >
      {work.time}
    </p>
    <Details
      css={css`
        grid-area: details;
      `}
      details={work.details}
    />
  </div>
);

const Details = ({ details, ...rest }) => (
  <ul {...rest}>
    {details.map(detail => (
      <li key={detail}>
        <Markdown>{detail}</Markdown>
      </li>
    ))}
  </ul>
);

const Header = Section.withComponent("header");

const globalStyles = css`
  html {
    font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI",
      Roboto, "Helvetica Neue", Arial, sans-serif;
  }
`;

const printStyles = css`
  @page {
    margin: 0.3in;
  }

  @media print {
    a {
      color: inherit !important;
      text-decoration: none !important;

      &:visited {
        color: inherit !important;
      }
    }
  }
`;

export default function Resume({ data }) {
  const workExperiences = data.workExperiences.edges.map(e => e.node);
  const openSourceProjects = data.openSourceProjects.edges.map(e => e.node);

  return (
    <>
      <Header>
        <Global styles={globalStyles} />
        <Global styles={printStyles} />
        <ContactGroup>
          <Name>Alex LaFroscia</Name>
          <Website>
            <a href="http://alexlafroscia.com">alexlafroscia.com</a>
          </Website>
          <Email>
            <a href="mailto:alex@lafroscia.com">alex@lafroscia.com</a>
          </Email>
        </ContactGroup>
      </Header>

      <Section>
        <SectionHeader>Work Experiences</SectionHeader>

        {workExperiences.map(work => (
          <Work key={work.company} work={work} />
        ))}
      </Section>

      <Section id="oss-projects">
        <SectionHeader>Notable Open Source Projects</SectionHeader>

        {openSourceProjects.map(project => (
          <div key={project.name}>
            <h3>
              <a href={`https://github.com/${project.name}`}>{project.name}</a>
            </h3>
            <Details details={project.details} />
          </div>
        ))}
      </Section>

      <Section>
        <SectionHeader>Academics</SectionHeader>
        <ul>
          <li>
            BS in Computed Science from University of Pittsburgh, College of
            Arts and Sciences, Class of 2016.
          </li>
        </ul>
      </Section>
    </>
  );
}

export const query = graphql`
  {
    openSourceProjects: allOpenSourceProjectsYaml {
      edges {
        node {
          name
          details
        }
      }
    }
    workExperiences: allWorkExperiencesYaml(filter: { hide: { ne: true } }) {
      edges {
        node {
          company
          role
          time
          details
        }
      }
    }
  }
`;
